# objetivo: dependencia(s)
# <tab> cmd1
# <tab> cmd2
# .
all: ejer1 ejer2 ejer3 ejer4 ejer5 

ejer1: ejer1.c
	gcc ejer1.c -o ejer1
	echo "Terminó la compilación del ejercicio 1"

ejer2: ejer2.c
	gcc ejer2.c -o ejer2
	echo "Terminó la compilación del ejercicio 2"

ejer3: ejer3.c
	gcc ejer3.c -o ejer3
	echo "Terminó la compilación del ejercicio 3"

ejer4: ejer4.c
	gcc ejer4.c -o ejer4
	echo "Terminó la compilación del ejercicio 4"

ejer5: ejer5.c
	gcc ejer5.c -o ejer5
	echo "Terminó la compilación del ejercicio 5"

#test: test.c
#	gcc test.c -o test
#	echo "Test compilado"
