# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra

# Targets (programs to compile)
TARGETS = ejer4

# Default target
all: $(TARGETS)

# Rule to compile each program
ejer1: ejer1.c
	$(CC) $(CFLAGS) -o $@ $<

ejer2: ejer2.c
	$(CC) $(CFLAGS) -o $@ $<

ejer3: ejer3.c
	$(CC) $(CFLAGS) -o $@ $<

ejer4: ejer4.c
	$(CC) $(CFLAGS) -o $@ $<


clean:
	rm -f $(TARGETS)



